name: Actualisation des événements ÉTS

# Quand est-ce que le robot s'active ?
on:
  schedule:
    - cron: '0 2 * * *' # Tous les jours à 2h du matin (Heure UTC)
  workflow_dispatch: # Permet d'ajouter un bouton pour le lancer manuellement sur GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest # Le serveur virtuel gratuit de GitHub
    
    steps:
      - name: 1. Récupérer le code de notre dépôt
        uses: actions/checkout@v3

      - name: 2. Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Installer les dépendances
        run: pip install -r requirements.txt

      - name: 4. Lancer le script de scraping
        run: python urls_manager.py 

      - name: 5. Sauvegarder le nouveau CSV et le renvoyer sur GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add evenements_ets.csv
          # S'il y a des changements, on crée une nouvelle sauvegarde (commit) et on l'envoie (push)
          git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour quotidienne des données" && git push)
